services:
    - postgresql
    - mysql

language: perl6

perl6:
    - latest
sudo: false
install:
    - rakudobrew build-panda
    - panda installdeps .
before_install:
    # mysql
    - mysql -e "CREATE DATABASE dbdishmysqltest;" -uroot
    - mysql -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpass';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON dbdishmysqltest.* TO 'testuser'@'localhost';" -uroot
    # Pg
    - psql -c 'create database travis_ci_test;' -U postgres
    - export PGDATABASE=travis_ci_test
    - export PGUSER=postgres
    - panda installdeps .
